### ISSUE TITLE
[Feature]: Trample Crops vs Trample Farmland

### ISSUE THREAD

**Issue by Unleashed75** [BVengo/anti-entity-grief#3]
### Request Description

I would like to see the Trample Crops rule only work on farmland that has crops on them.

The current Trample Crops rule stops trampling farmland, regardless of crops being on top of it or not.
If the farmland has no crops on it, I would need to place blocks on top and break them, or remove water source but this may not be easy if the farmland is by a river etc.
This acts more like a Trample Farmland rule.

A true Trample Crops rule would be only when farmland has no crops on top, can it be trampled.
This means if I placed farmland and crops in the wrong spot, I just have to remove the crop and jump on the farmland a couple times.

Maybe have the option for both, or rename to suit what it really does?

Great mod either way. Thank you!

**Comment by BVengo** [comment]
Great addition! I wasn't sure if anyone would want this split, but I should definitely be able to turn this into two configs instead.

**Comment by BVengo** [comment]
Making a note of my current dev implementation before it makes it into a release.

- **TRAMPLE_FARMLAND**: Can the entity turn farmland into dirt?
- **TRAMPLE_CROPS**: Can the entity kill crops?

I'll refer to these as F (TRAMPLE_FARMLAND) and C (TRAMPLE_CROPS) for the below.

So, the possible combinations are:
- **FC**: Normal behaviour, since destruction of farmland and crops are both allowed. Trampling farmland will turn it into dirt and the crops will be dropped.
- **F**: Cannot destroy crops. Will only turn farmland into dirt if it has no crops above it.
- **C**: Cannot destroy farmland. Will still destroy crops when farmland is (normally) supposed to be turned into dirt.
